# Application Settings
application_settings:
  threads: 5
  cpu_thread_count: 1
  database_url: "sqlite://./database.sqlite3"
  skip_logged_accounts: true
  shuffle_accounts: true
  generate_random_pass: true # only for <<Set password>> module
  check_uniqueness_of_proxies: true

# Attempts and Delay Settings
attempts_and_delay_settings:
  error_delay: 5 # seconds
  delay_before_start:
    min: 0 # seconds
    max: 0 # seconds

  delay_between_verification_nodes:
    min: 1 # minutes
    max: 1 # minutes

  max_register_attempts: 3
  max_login_attempts: 3
  max_stats_attempts: 3
  max_set_password_attempts: 3
  max_proxy_change_attempts: 2
  max_connect_wallet_attempts: 3
  max_verification_nodes_attempts: 3

  max_websocket_connect_attempts: 10
  delay_after_websocket_connect_attempts:
    min: 300 # seconds
    max: 600 # seconds

# Nodes Settings
nodes_settings:
  enable_nodes_verification: false

  active_nodes_per_account:
    min: 2
    max: 3

  min_proxy_score: 50

# Login Settings
login_settings:
  auth_by: "password"


# Captcha Settings
captcha_settings:
  two_captcha_api_key: ""
  anti_captcha_api_key: ""
  capsolver_api_key: ""

  captcha_service: "capsolver" # 2captcha, anticaptcha, capsolver


# Redirect Settings
redirect_settings:
  enable: false
  email: ""
  password: ""
  imap_server: ""

# IMAP Settings
imap_settings:
  use_proxy_for_imap: false
  use_single_imap:
    enable: false
    imap_server: "imap.gmx.net"

  servers:
    gmail.com: imap.gmail.com
    yahoo.com: imap.mail.yahoo.com
    icloud.com: imap.mail.me.com
    mail.ru: imap.mail.ru
    rambler.ru: imap.rambler.ru
    gmx.com: imap.gmx.com
    gmx.net: imap.gmx.net
    gmx.de: imap.gmx.net
    onet.pl: imap.poczta.onet.pl
    onet.com.pl: imap.poczta.onet.pl
    op.pl: imap.poczta.onet.pl